version: '3.8'

services:
  qtms-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quantum-time-messaging
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - 63424:3000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
